// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zayaufynifjyskbspshf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheWF1ZnluaWZqeXNrYnNwc2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTg2NzQsImV4cCI6MjA2MDIzNDY3NH0.Zy0emiWwRPgni4wWSv8ffPwcwiynTtPZe-S8kvjHop8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);